-- Cria a base de dados Companhia
CREATE DATABASE Advocacia;

-- Coloca a base de dados advocacia em uso
USE Advocacia;

-- Cria a tabela advogado (Nicolas)
CREATE TABLE ADVOGADO (
	OAB			VARCHAR(15)			NOT NULL UNIQUE, 
	IDRAMO		CHAR(10)					,
	PNOME		VARCHAR(20)			NOT NULL,
    MNOME		CHAR(5)						,
    SNOME		VARCHAR(30)			NOT NULL,
	TELEFONE	VARCHAR(20)					,
	EMAIL		VARCHAR(50)					,
	ENDERECO	CHAR(40)					,
    PRIMARY KEY (OAB)
    );

CREATE TABLE RAMO (
	ID		VARCHAR(10)				NOT NULL UNIQUE,
    RAMO	CHAR(30)				NOT NULL UNIQUE,
    PRIMARY KEY (ID)
    );

CREATE TABLE PESSOAS (
	CPF			VARCHAR(20)			NOT NULL UNIQUE, 
	PNOME		VARCHAR(20)			NOT NULL,
    MNOME		CHAR(5)						,
    SNOME		VARCHAR(30)			NOT NULL, 
	CEP			CHAR(10)					, 
	TELEFONE	VARCHAR(20)					,
	EMAIL		VARCHAR(50)					,
    ENDERECO	CHAR(40)					,
    PRIMARY KEY(CPF)
);

CREATE TABLE AUTOR (
	CPFAUTOR	VARCHAR(20)			NOT NULL UNIQUE, 
	PNOME		VARCHAR(20)			NOT NULL,
    MNOME		CHAR(5)						,
    SNOME		VARCHAR(30)			NOT NULL,
	CEP			CHAR(10)					, 
	TELEFONE	VARCHAR(20)					,
	EMAIL		VARCHAR(50)					,
    ENDERECO	CHAR(40)					,
    PRIMARY KEY (CPFAUTOR)
);


CREATE TABLE REU (
	CPFREU		VARCHAR(20)			NOT NULL UNIQUE, 
	PNOME		VARCHAR(20)			NOT NULL,
    MNOME		CHAR(5)						,
    SNOME		VARCHAR(30)			NOT NULL, 
	CEP			CHAR(10)					, 
	TELEFONE	VARCHAR(20)					,
	EMAIL		VARCHAR(50)					,
    ENDERECO	CHAR(40)					,
    PRIMARY KEY (CPFREU)
);

ALTER TABLE REU ADD FOREIGN KEY (CPFREU) REFERENCES PESSOAS(CPF);

-- Nicolas
CREATE TABLE JUIZ (
	CPFJUIZ		VARCHAR(20)			NOT NULL UNIQUE, 
	PNOME		VARCHAR(20)			NOT NULL,
    MNOME		CHAR(5)						,
    SNOME		VARCHAR(30)			NOT NULL, 
	CEP			CHAR(10)					, 
	TELEFONE	VARCHAR(20)					,
	EMAIL		VARCHAR(50)					,
    ENDERECO	CHAR(40)					,
    PRIMARY KEY(CPFJUIZ),
    FOREIGN KEY (CPFJUIZ) REFERENCES PESSOAS(CPF)
);

-- Cria a tabela caso (Nicolas)
CREATE TABLE CASO (
	NPROCESSO	CHAR(30)		NOT NULL,  -- possui caracteres especiais
    IDJUIZ		VARCHAR(20)		NOT NULL,
	ANO			INT(4)			NOT NULL, 
	REU			VARCHAR(50)		NOT NULL, 
	COMARCA		CHAR(35)				,
    VARA		VARCHAR(40)				,
	PRIMARY KEY (NPROCESSO)				,
	FOREIGN KEY (IDJUIZ) REFERENCES JUIZ(CPFJUIZ)
);

CREATE TABLE TEM(
	CPF		VARCHAR(20),
    PRIMARY KEY (CPF),
    FOREIGN KEY  (CPF) REFERENCES PESSOAS(CPF)
    );
    
CREATE TABLE JULGAM(
	CPF				VARCHAR(20) ,
    DIAMESANO		DATE		,
    SENTENCA		VARCHAR(50) ,
    PRIMARY KEY (CPF),
    FOREIGN KEY (CPF) REFERENCES PESSOAS(CPF)
);

CREATE TABLE TRABALHA_EM(
	REGISTRO_OAB	VARCHAR(15) NOT NULL	,
    NPROCESSO		CHAR(30) 	NOT NULL	,
    PRIMARY KEY (REGISTRO_OAB, NPROCESSO)	,
    FOREIGN KEY (REGISTRO_OAB) REFERENCES ADVOGADO(OAB),
    FOREIGN KEY (NPROCESSO) REFERENCES CASO(NPROCESSO)
);